### ISSUE TITLE
Website icons not showing up

### ISSUE THREAD

**Issue by emersion** [bilelmoussaoui/Authenticator#16]
**Reporter info**

```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - Gnome
```

**Gnome TwoFactorAuth version** 0.1.1

**Actual issue**

![screenshot from 2016-07-18 00-02-35](https://cloud.githubusercontent.com/assets/506932/16903292/ba7252ae-4c7a-11e6-9115-3a603ec69cbc.png)

**Steps to reproduce (if you knew)**

Click "+".

**Other Note (feature-request, question, etc...)**

**Comment by bil-elmoussaoui** [comment]
I use the icon from the theme if your theme provide one. If not i use the pre-shiped icons with the application. But there's a lot of missing icons and my design skills are really not good at all..maybe someone  else might want to get this fixed in the near future? 
If you have any idea, don't hesitate :)

**Comment by emersion** [comment]
* You should add a default icon representing a generic app/website
* ALL icons are like this, even those normally shipped with the app

**Comment by bil-elmoussaoui** [comment]
@emersion I will add a generic app/website later or maybe use the application logo? But again i don't have any design skills to design any icon..
Can you paste a screenshot of the Twitter or Steam or any other application that have a shipped icon with?

**Comment by emersion** [comment]
Better to use icons from theme instead of designing a new one. It integrates better with the DE.

Here is a screenshot:

![screenshot from 2016-07-18 17-57-17](https://cloud.githubusercontent.com/assets/506932/16921276/1a8f80f8-4d11-11e6-9642-25abeebcc4df.png)

**Comment by bil-elmoussaoui** [comment]
Well i use the ones from the theme, but as you're using the default theme. Those icons are not supported...Try an other theme like Paper or Numix-Circle?

**Comment by emersion** [comment]
I don't think saying to users "don't use the official GNOME icon theme" can be a fix for a GNOME app.

You could check for your icon-specific theme icons, and fallback on official ones if not available.

**Comment by emersion** [comment]
BTW, Twitter icon not showing up is another different issue. It should load as it's bundled.

**Comment by bil-elmoussaoui** [comment]
Thats why im looking for someone to design all the missing icons so they
can be instwlled to the fallback theme! I will take a look and see what
causes twitter icon not being shown

**Comment by bil-elmoussaoui** [comment]
@emersion Can you check if you can find any file in `/usr/local/share/twofactorauth/applications/images/`?

**Comment by emersion** [comment]
Nothing here. `/usr/local/share/twofactorauth` does not exist.

**Comment by bil-elmoussaoui** [comment]
Sorry for the delay! i will fix the makefile very soon

**Comment by bil-elmoussaoui** [comment]
@emersion This issue should be now fixed. At least for the icons not being detected. For adding a default icon or cover all those icons. I would really like if a designer could at least add the most common brands and a default one for the rest. But I suck at that. so, I cannot do anything about it, see #9....

**Comment by matteotanca** [comment]
![image](https://user-images.githubusercontent.com/5741224/37824447-eec59b7e-2e8c-11e8-8985-628d63112f79.png)

same here! Only Dropbox icon is shown

**Comment by bilelmoussaoui** [comment]
@matteotanca As explained, I can't do anything about it other than providing some default icon... there's a lot of icons that should be designed, and I have no skills to do so. Plus the current shown icons are loaded from the current theme you're using

**Comment by matteotanca** [comment]
Not a real problem for me :)

**Comment by matteotanca** [comment]
![image](https://user-images.githubusercontent.com/5741224/37825159-258c49a8-2e8f-11e8-8a8d-ae8b50b3f330.png)

The only problem is that if I have no icons then I cannot identify the right one service.

However it works, those are facebook and gmail services.

**Comment by bilelmoussaoui** [comment]
Let me check that too. It seems to be a different issue, can you open a new one so I can close it once it's fixed? (more for the future users who might report the same issue)

**Comment by bilelmoussaoui** [comment]
Falling back to the application logo as a fallback image until someone provides some help with designing a better fallback icon
