### ISSUE TITLE
Build and distribute

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/Authenticator#27]
For at least fedora, archlinux and ubuntu! 
- [ ] Archlinux
- [ ] Fedora
- [ ] Solus 
- [ ] Debian/Ubuntu

**Comment by theel0ja** [comment]
Debian/Ubuntu should be ticked.

http://www.getdeb.net/software/gnome-twofactorauth

**Comment by bilelmoussaoui** [comment]
The app should be available pretty soon as a flatpak package and on elementary appcenter. Other than this, I'm not planning to support any other platform...
Packaging on Debian and Fedora was always a pain for me.

**Comment by lll2yu** [comment]
@bilelmoussaoui I made an AUR package for Archlinux <a href="https://aur.archlinux.org/packages/authenticator/">here</a>. You can tick that if you are still interested in packaging  for Archlinux.

**Comment by lll2yu** [comment]
@bilelmoussaoui I didn't realise that the project underwent a change of name and there already exists `gnome-twofactorauth` in AUR. Sorry for creating a duplicate package. 

Do you still consider updating that package or shall I keep my package up?

**Comment by bilelmoussaoui** [comment]
Keep your package up! Thanks 😊

**Comment by bilelmoussaoui** [comment]
Keep your package up! Thanks 😊

**Comment by bilelmoussaoui** [comment]
@lll2yu Can you please remove the `pyaml` dependency? It's not needed anymore. Somehow, I forgot to remove it from the README

**Comment by lll2yu** [comment]
@bilelmoussaoui Yes, updated accordingly.
