### ISSUE TITLE
No module named 'Authenticator.interfaces'

### ISSUE THREAD

**Issue by MrTimscampi** [bilelmoussaoui/Authenticator#34]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - Gnome 3.24
 ```

**Gnome TwoFactorAuth version**

Latest commit

**Actual issue**

Following the instructions then running the software yields the following error:  

```
Traceback (most recent call last):
  File "/usr/local/bin/gnome-authenticator", line 27, in <module>
    from Authenticator import application
  File "/usr/lib/python3.5/site-packages/Authenticator/application.py", line 25, in <module>
    from Authenticator.widgets.window import Window
  File "/usr/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 25, in <module>
    from Authenticator.widgets.accounts_window import AccountsWindow
  File "/usr/lib/python3.5/site-packages/Authenticator/widgets/accounts_window.py", line 25, in <module>
    from Authenticator.models.account import Account
  File "/usr/lib/python3.5/site-packages/Authenticator/models/account.py", line 3, in <module>
    from Authenticator.interfaces.account_observrable import AccountObservable, AccountRowObservable
ImportError: No module named 'Authenticator.interfaces'
 ```

**Steps to reproduce (if you knew)**

- Follow build instructions
- Launch the software

**Other Note (feature-request, question, etc...)**

The import is looking for a file that doesn't exist.  
I'm launching using Python 3.5.3.

**Comment by bil-elmoussaoui** [comment]
The code on master isn't full working for now. I'm working on a better version, should land pretty soon !

**Comment by bil-elmoussaoui** [comment]
Sorry for the long delay. I have rewrote the code from scratch, with a better code quality and less bugs. 
I will to improve it as must as i can before pushing the code to master with a new release :)

**Comment by bilelmoussaoui** [comment]
Fixed on master. A new release is coming out pretty soon!
