### ISSUE TITLE
Cannot configure Dropbox service

### ISSUE THREAD

**Issue by matteotanca** [bilelmoussaoui/Authenticator#41]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 
 * Desktop environment - Gnome Shell 3.26
 ```

**Authenticator version**

**Actual issue**

Cannot configure Dropbox account. Cannot scan or enter manually the secret code. 

![selezione_016](https://user-images.githubusercontent.com/5741224/37824764-fd08dbb4-2e8d-11e8-8eeb-7a8f7d266bae.png)

**Steps to reproduce (if you knew)**

Try to configure Dropbox 2fa service.

**Other Note (feature-request, question, etc...)**

**Comment by bilelmoussaoui** [comment]
Let me check that right now!

**Comment by bilelmoussaoui** [comment]
Fixed on master.
