### ISSUE TITLE
Configured Service Names or Images not shown

### ISSUE THREAD

**Issue by matteotanca** [bilelmoussaoui/Authenticator#43]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version -
 * Desktop environment - Gnome 3.26
 ```

**Authenticator version**

**Actual issue**

![image](https://user-images.githubusercontent.com/5741224/37826166-ad465a0c-2e92-11e8-9b84-e328d2cef0b4.png)

In the service configured list I have not a name or a Image to distinguish my services.

**Steps to reproduce (if you knew)**

**Other Note (feature-request, question, etc...)**

**Comment by matteotanca** [comment]
Also, many of us, like me, do use more than one account for each service. Can we set a name for the configured services? So I can use for example : gmail work, gmail personal etc etc

**Comment by bilelmoussaoui** [comment]
Will definitely add that. Do you have any idea where the "account name" should be shown?

**Comment by matteotanca** [comment]
I think same place where is writing "image-missing" should be fine.

**Comment by SenlisO** [comment]
I have the same issue.
Ubuntu: 16.04
Desktop: Plasma 5

I would also prefer an account name being displayed instead of "image-missing".  When I add use Google Auth to add a QR code, the app picks up on the service name and user name.  Isn't that info embedded in the QR code?

**Comment by bilelmoussaoui** [comment]
![screenshot from 2018-03-24 11-53-57](https://user-images.githubusercontent.com/7660997/37863170-218537d6-2f5a-11e8-9f6d-6e30ea5f291e.png)

![screenshot from 2018-03-24 11-54-14](https://user-images.githubusercontent.com/7660997/37863169-213227bc-2f5a-11e8-975f-091a1bcbc829.png)

How does it look like?

@SenlisO It's more of a bug in the app itself. Working on it currently.

**Comment by bilelmoussaoui** [comment]
Fixed on master.

**Comment by bilelmoussaoui** [comment]
Repoen, if you have any other issues. The new release should be available by tomorrow on flathub! Still need to figure out how to get ride of gnome-screenshot.

**Comment by RoyiAvital** [comment]
Is there a list of services supported by this application?

**Comment by matteotanca** [comment]
https://github.com/bilelmoussaoui/Authenticator#credits

Credits
Applications/Websites database are from twofactorauth, by 2factorauth team
