### ISSUE TITLE
Authentication for Facebook not working

### ISSUE THREAD

**Issue by netsatan** [bilelmoussaoui/Authenticator#47]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.3
 * Desktop environment - Unity
 ```

**Authenticator version**
0.2

**Actual issue**
Facebook code does not work - I can scan the Facebook's QR, add it in the app, but whenever I paste back the code I get from Authenticator I get "Please try again". Tried on both Firefox and Vivaldi.

**Steps to reproduce (if you knew)**
1. Add Facebook account using Authenticator,
2. Try to confirm the app using the generated code. 

**Other Note (feature-request, question, etc...)**
n/a

**Comment by bilelmoussaoui** [comment]
Just tried it using the latest master commit and it works correctly. It seems to be somehow the same issue as #41. Will release a new version pretty soon. Please reopen this if you still have the same issue on 0.3 (to be released)
