### ISSUE TITLE
no names on services

### ISSUE THREAD

**Issue by Dea1993** [bilelmoussaoui/Authenticator#49]
**Reporter info**

 ```
 * Distribution - Fedora 27 (I've tested both xorg and wayland)
 * Desktop environment - Gnome Shell 3.26
 ```

**Authenticator version**
0.2.1 (from flathub)

**Actual issue**

name of service is not shown.
I've only one service, so i know what service it is, but if I had a lot of services, i can't know it, so i can't use this application
![schermata da 2018-03-25 09-24-03](https://user-images.githubusercontent.com/5217483/37878700-54976194-306d-11e8-8ae4-c6bc18f20330.png)

**Steps to reproduce (if you knew)**
Add e new service (for example protonmail), Configure it, restart application

**Comment by bilelmoussaoui** [comment]
Already fixed that on master. I'm going to release 0.3 pretty soon which should include a fix for that too.

**Comment by Dea1993** [comment]
thanks.
i'm waiting for the update
