### ISSUE TITLE
Secret tken

### ISSUE THREAD

**Issue by Caver1** [bilelmoussaoui/Authenticator#52]
**Reporter info**

 ```
 * Distribution -Ubuntu 16.04
 * Gtk+ 3.0 version -3.18.9 ?
 * Desktop environment -Unity
 ```

**Authenticator version**0.2

**Actual issue**

**Steps to reproduce (if you knew)**

**Other Note (feature-request, question, etc...)**
Secret token for an account. How to aquire one?

**Comment by bilelmoussaoui** [comment]
It depends on the account you want to use. Which one you want to use in your case ?

**Comment by Caver1** [comment]
Lastpass right now. Hopefully that will give me a clue for others I might want.

**Comment by bilelmoussaoui** [comment]
https://helpdesk.lastpass.com/multifactor-authentication-options/

**Comment by Caver1** [comment]
That's fine except your Authenticator isn't mentioned there. I'm sorry maybe I'm blind but there is no mention of a secret token for any of the authenticators list there.
Thanks for replying.
Doug

**Comment by bilelmoussaoui** [comment]
Let me check that out

**Comment by bilelmoussaoui** [comment]
It seems that lastpass only allows using Google Authenticator or some other apps.
