### ISSUE TITLE
add andOTP support

### ISSUE THREAD

**Issue by YangtseSu** [bilelmoussaoui/Authenticator#53]
Implement:

    import
    export

**Comment by bilelmoussaoui** [comment]
How do you like this to be implemented? I was thinking about adding some basic import & export stuff. But it will contain some sensitive information about your accounts. Still trying to figure out how to do this in the most secure way.
I'm going to install andOTP and see if it's possible for me to export/import the data from Authenticator to andOTP

**Comment by YangtseSu** [comment]
https://github.com/andOTP/andOTP
Backup and restore data is very necessary for OTP software. It is also necessary to synchronize between different software. I can't hold the computer forever, right?

AndOTP is free and open source.The backup data use the JSON format.

**Comment by neurolit** [comment]
In andOTP, exports can be encrypted (with PGP or a passphrase) before being saved. It's a fantastic feature.

**Comment by bilelmoussaoui** [comment]
Can you guys try this branch ? https://github.com/bilelmoussaoui/Authenticator/tree/backup It has just the basic import/export as JSON files. The files are not encrypted currently. Will add other options as encrypt with a paraphrase or with a PGP later
