### ISSUE TITLE
Feature Request:change label

### ISSUE THREAD

**Issue by YangtseSu** [bilelmoussaoui/Authenticator#54]
Feature Request:change label

**Comment by bilelmoussaoui** [comment]
Which label you're talking about?

**Comment by YangtseSu** [comment]
https://github.com/bilelmoussaoui/Authenticator/blob/master/data/screenshots/screenshot1.png

dropbox youtube

**Comment by bilelmoussaoui** [comment]
Already on master. See https://github.com/bilelmoussaoui/Authenticator/issues/43#issuecomment-375871334
Will be available on 0.3
