### ISSUE TITLE
not working on ubuntu

### ISSUE THREAD

**Issue by Gy0m** [bilelmoussaoui/Authenticator#55]
**Reporter info**

 * Ubuntu 17.10
 * Gtk+ 3.0 version -
 * Mate desktop -

Hi i installer flatpack on my system the app was intalled with icon in menulibre but i can see that the app is starting but it ends and the app won't start.

I also try compiling but it ends with an error code.

Have you any idea, this app is hyping me a lot

**Actual issue**

**Steps to reproduce (if you knew)**

**Other Note (feature-request, question, etc...)**

**Comment by bilelmoussaoui** [comment]
Can you run the application from terminal using 
```
flatpak run com.github.bilelmoussaoui.Authenticator
```
And paste the output here?
Before doing so, you can always try to upgrade the applications installed using fatpak `fatpak update`
I have released 0.3 few days ago which fixed an issue with Unity and DE other than GONME.

**Comment by Gy0m** [comment]
I had to make a clean install of ubuntu mate 17.10 i followed the doc for flatpack : 

> https://flatpak.org/setup/Ubuntu/

Then run `flatpak install flathub com.github.bilelmoussaoui.Authenticator` and now it works perfect

Sadly night mode don't work and i only have v0.2  but it's not a big issue and app is stil in work. I with you all my best and this could be a great app

**Comment by bilelmoussaoui** [comment]
0.3 is not released yet. And the night mode depends on the theme you're using currently

**Comment by Gy0m** [comment]
Ok great i use dark gtk but app works and it's the best it can do :)
