### ISSUE TITLE
New service added successfully, yet it have name "image-missing" in the list and sometimes codes is not generated

### ISSUE THREAD

**Issue by RussianNeuroMancer** [bilelmoussaoui/Authenticator#63]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - Gnome 3.28
 ```

**Authenticator version**
0.2.1

I installed Authenticator and added same service with same code on two devices. On one device Authenticator doesn't use installed Gnome theme (I not sure if this Authenticator, Flatpak or Gnome issue, so this theme problem is just note here, not bugreport) but service added and generated codes are correct. On another device I did same steps which for some reason lead to "image-missing" item name in the list with no way to rename it. Also sometimes codes is not generated, but app restart or removing service and adding it again fixes this for some reason. Curiously, sometimes after re-adding service instead of "image-missing" I get secret 2FA code as item name. 

**Actual issue**

1. Incorrect item name ("image-missing" or secret 2FA code) in the list instead of service name.
2. Occasionally codes is not generated.
3. There is no spacing between code and "Expires in N seconds" string and no way to change window side. Could be related to the fact that I have to set 1.25 fonts size in Gnome Tweak Tool which is necessary due to device screen size (8 inch HD display).

**Comment by bilelmoussaoui** [comment]
Already fixed on master.
