### ISSUE TITLE
Adding an account doesn't work

### ISSUE THREAD

**Issue by SolarLiner** [bilelmoussaoui/Authenticator#64]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - GNOME Shell
 ```

**Authenticator version**
0.2

**Actual issue**
Adding a new account doesn't actually use the given title, or worse, uses the token as the title. Furthermore, the generated tokens don't work, if they're generated at all.

**Steps to reproduce (if you knew)**
1. Add a new account
1. Enter the secret (haven't tested with QR Codes, being on Wayland and all), and give a meaningful title
1. ???
1. The title doesn't match and if the app can generate codes, they won't be accepted.

https://gfycat.com/WellgroomedVeneratedArmyworm

**Other Note (feature-request, question, etc...)**
I can reproduce the bug on fresh installs of the app on both my desktop PC and my laptop. I had just installed the app on my desktop but my laptop already had some use before the bug appeared. Both installs were made through Flatpak.

**Comment by bilelmoussaoui** [comment]
Already fixed on master.
