### ISSUE TITLE
zbar alternative ?

### ISSUE THREAD

**Issue by Devil505** [bilelmoussaoui/Authenticator#65]
I requested to Solus dev team to package authenticator but it seems zbar is too old for them

See https://dev.solus-project.com/T6165

Any solutions ?

**Comment by bilelmoussaoui** [comment]
Zbar is used only for  QR scan feature. I'm going to  make it an optional dependency in the next release. I couldn't find something easy to package and use. 

Will keep this open in order to check again for any alternatives

**Comment by natanielcz** [comment]
Maybe take a look at https://pypi.org/project/PyQRCode

**Comment by bilelmoussaoui** [comment]
@natanielcz  It's only a QRCode encoder, need something to decode without having to install a lot of libraries.

**Comment by bignose-debian** [comment]
Everyone seems to rely on the 'zbar' project, which appears moribund upstream (at the SourceForge project page).

The ['pyzbar' library](https://pypi.org/project/pyzbar/) looks promising:

> Read one-dimensional barcodes and QR codes from Python 2 and 3 using the zbar library.
>
> The older zbar package is stuck in Python 2.x-land. The zbarlight package doesn’t provide support for Windows and depends upon Pillow.

So they acknowledge the failings of the official 'zbar' Python bindings, and provide better ones (including for Python 3).

**Comment by bilelmoussaoui** [comment]
@bignose-debian I'm using pyzbar currently too.

**Comment by bilelmoussaoui** [comment]
Closing this as I'm not going to provide any pyzbar alternative anytime soon. I'm just going to mark the dependency as optional in the next version
