### ISSUE TITLE
No provider icons when installing from flatpak

### ISSUE THREAD

**Issue by mt7479** [bilelmoussaoui/Authenticator#66]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version -
 * Desktop environment - Gnome
 ```

**Authenticator version**
0.2

**Actual issue**
No provider icons when installing from flatpak

**Steps to reproduce (if you knew)**
as root:

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.github.bilelmoussaoui.Authenticator

**Other Note (feature-request, question, etc...)**
Also the flatpak version ships 0.2 while the is a 0.2.1 version available in the releases section.

**Comment by bilelmoussaoui** [comment]
Already fixed on master. Will try to fix some issues as soon as I can and push a new release.
