### ISSUE TITLE
Screenshot images do not pass tests

### ISSUE THREAD

**Issue by bucefal91** [bilelmoussaoui/Authenticator#67]
**Reporter info**
Hi :) I am working on including your application within Gentoo Linux. It is mostly done and the only thing I found is that current screenshot images do not pass validation.

**Authenticator version**
Master branch

**Actual issue**
The tests fail complaining about the screenshot images. Namely, error messages are:
• attribute-invalid     : <screenshot> width too small [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot1.png] minimum is 624px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot1.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot1.png]
• attribute-invalid     : <screenshot> width too small [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot2.png] minimum is 624px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot2.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot2.png]
• attribute-invalid     : <screenshot> width too small [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot3.png] minimum is 624px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot3.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot3.png]
• attribute-invalid     : <screenshot> width too small [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot4.png] minimum is 624px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot4.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/bilelmoussaoui/Authenticator/master/data/screenshots/screenshot4.png]

**Steps to reproduce (if you knew)**
I believe just running meson tests is enough. The actual command where it brakes down is `/usr/bin/appstream-util validate /var/tmp/portage/gnome-extra/authenticator-9999/work/authenticator-9999-build/data/com.github.bilelmoussaoui.Authenticator.appdata.xml`

**Comment by bilelmoussaoui** [comment]
Will update those screenshots for the next release. Thanks for reporting! For now, you can pass the tests as they won't break anything.

**Comment by bucefal91** [comment]
Thank you, very kind of you. Yes, both tests are rather superficial. I've excluded the one for `.appdata.xml` and the one for `.desktop` file passes successfully within Gentoo package manager.

I really love your app :)

**Comment by bilelmoussaoui** [comment]
Fixed on master!
