### ISSUE TITLE
Typing in "New Account" dialogue doesn't start search

### ISSUE THREAD

**Issue by hadess** [bilelmoussaoui/Authenticator#77]
Using 0.2.2.1 from Flathub, typing in the new account dialogue doesn't start a search. See `gtk_search_bar_handle_event()` and `gtk_search_bar_connect_entry()` for how to hook that up.

**Comment by bilelmoussaoui** [comment]
Totally forgot to do that. Will fix that on the next minor version.

**Comment by bilelmoussaoui** [comment]
I have re-implemented the add new account window. This is not an issue anymore.
