### ISSUE TITLE
Ability to edit a record

### ISSUE THREAD

**Issue by dannosaur** [bilelmoussaoui/Authenticator#82]
It would be nice to be able to edit a record once it's been added. I realise that most TOTP apps don't let you edit the details once they've been added, but this currently/solely relies on the user typing something in.

Not suggesting you're able to edit the secret code once it's in, that bit should remain a secret and never displayed back to the user, but I still think it'd be a good idea to be able to edit the provider name and/or the identity/username (say for instance I typed it wrong and saved the record).

Also as a secondary to this, most QR codes have the provider/identity details baked into them, so it'd be cool to be able to pick this information up and pre-populate the provider/identity fields with this information, if the QR code is scanned and the data is available. Not sure how feasible this might be.

**Comment by bilelmoussaoui** [comment]
There's a working prototype on the `new-main-window` branch. Can you try that out?

**Comment by bilelmoussaoui** [comment]
Fixed on master.
