### ISSUE TITLE
Codes being displayed on screen

### ISSUE THREAD

**Issue by dannosaur** [bilelmoussaoui/Authenticator#84]
Is there any reason why the codes are displayed using a password-style label, whereby seemingly clicking on it gets the code to display? I'm not sure I see the purpose of this - it's not like any other TOTP application proactively "hides" the codes from view until the user indicates that they want to see the code. Sure you have the copy button, and you can click on the dots to see the code, I just feel it's an unnecessary extra step.

**Comment by bilelmoussaoui** [comment]
I just thought it was something secret that shouldn't be displayed. I'm not sure if it should be kept or it needs a better design maybe?

**Comment by dannosaur** [comment]
I'm torn with this to be honest. On the one hand it technically *is* a password, but at the same time no other authenticator apps hide the codes, and it's not like knowing what the codes are for your accounts serves any real purpose - they change every 30 seconds so unless the accompanying password is also known, it's useless.

I'm leaning more towards the "display the codes prominently" idea. The whole purpose of this app is the codes, they need to be front and center. A user unfamiliar with the app might not understand that clicking on the code reveals it so at that point is probably inclined to uninstall it and find something else that gives them the codes they're after, possibly thinking that this only provides a "copy" function and has no other way of revealing the codes. Remember that not all users RTFM ;)

It's not intuitive at all and imho should be displayed prominently at all times.

**Comment by bilelmoussaoui** [comment]
Totally agree. This was fixed on the new branch `new-main-window`

**Comment by bilelmoussaoui** [comment]
Fixed on master.
